# OWNER: SIMD implementer (Phase 3). See docs/decisions.md and
# Julia-Microkernel-Tile-Interface-Design.md sections 7-9, 12.
#
# Implements: one explicit-SIMD execute_tile! candidate (using SIMD.jl's
# Vec{N,T}), matching src/kernel.jl's (ScalarKernel's) packed-format contract
# and public API exactly: zero_accumulator, accumulate, store_tile!,
# execute_tile!, plus the mr/nr/scalartype/packed_*_offset/packed_*_length and
# pack_a!/pack_b! forwarding every concrete kernel wrapping a KernelDescriptor
# needs (see docs/decisions.md, Phase 2 integration note #2).
#
# --- Why a new type instead of reusing ScalarKernel ---
#
# Design doc section 8: "For the SIMD kernel, represent accumulators as
# statically identifiable vector values, typically an immutable tuple. An
# ordinary heap array of accumulators is not the intended fast path." This is
# the one thing that must differ from src/kernel.jl: `SIMDKernel` wraps the
# same frozen `KernelDescriptor{MR,NR,T}` (src/kernel_descriptor.jl) but adds
# a fourth, SIMD-only type parameter `W` (vector lane width) and an
# accumulator representation of `NTuple{NVECA*NR, SIMD.Vec{W,T}}` where
# `NVECA = MR ÷ W` (the number of full-width A vectors per output column —
# section 5's illustrative MR=8, NR=6, W=4 gives NVECA=2, NV=12, matching
# "two A vectors ... twelve accumulator vectors" exactly). `MR` must be a
# multiple of `W` (checked at construction); `NR` need not be.
#
# --- Register residency (design doc section 8/12) ---
#
# The K-step body (one vector load of A, NR scalar loads of B, NVECA*NR FMAs)
# is generated by `@generated function _accumulate_step` as a single
# straight-line, fully unrolled expression with *no* closures capturing the
# reassigned `acc` tuple: the classic Julia performance trap here is a
# `do`-block closure over a variable that is reassigned once per loop
# iteration, which the compiler must box because it cannot prove the closure
# doesn't outlive the binding. `_accumulate_step` sidesteps this entirely —
# it is an ordinary (non-closure) function call inside `accumulate`'s `for p`
# loop, so `acc = _accumulate_step(...)` is a plain reassignment of a local
# variable, never boxed. See the "Allocation and generated-code checks"
# section of this file's test file for the actual @code_typed/@code_llvm/
# @allocated inspection this claim rests on (design doc section 12: "Do not
# silently treat source-level tuples as proof of register execution").

using SIMD: Vec, vload, vstore

# ----------------------------------------------------------------------------
# SIMDKernel type
# ----------------------------------------------------------------------------

"""
    SIMDKernel{MR,NR,T,W}(descriptor::KernelDescriptor{MR,NR,T})
    SIMDKernel(::Val{MR}, ::Val{NR}, ::Type{T}, ::Val{W})
    SIMDKernel(::Val{MR}, ::Val{NR}, ::Type{T})

Explicit-SIMD microkernel for register-tile shape `(MR, NR)`, scalar type `T`,
using `SIMD.Vec{W,T}` as its vector lane. Wraps a `KernelDescriptor` (the
frozen shape/packed-format contract, unchanged from `ScalarKernel`) and adds
a fourth type parameter `W`, the vector width, plus the SIMD accumulator
representation (see this file's header comment).

`MR` must be a multiple of `W` (checked at construction: `mr(kernel)` values
of A are consumed as `MR ÷ W` full-width vectors per K step, so a remainder
would leave some physical rows unaddressed by any vector). `NR` need not be
a multiple of anything — B contributes one *scalar* value per column per K
step (design doc section 5's illustrative shape), broadcast against each A
vector via `SIMD.jl`'s `muladd(::Vec, ::ScalarTypes, ::Vec)` method, not
loaded as its own vector.

The 4-argument constructor lets a caller pick `W` explicitly; the 3-argument
form defaults to [`_default_lanewidth`](@ref) for `T` (4 for `Float64`, 8 for
`Float32` — one 256-bit-register's worth of lanes; an ordinary
implementation choice, not a tuning claim, and callers needing a different
width for their hardware should use the 4-argument form).
"""
struct SIMDKernel{MR,NR,T,W}
    descriptor::KernelDescriptor{MR,NR,T}

    function SIMDKernel{MR,NR,T,W}(descriptor::KernelDescriptor{MR,NR,T}) where {MR,NR,T,W}
        W isa Int && W > 0 ||
            throw(ArgumentError("SIMDKernel requires an Int vector width W > 0, got W = $W"))
        mod(MR, W) == 0 ||
            throw(ArgumentError("SIMDKernel requires mr(kernel) = $MR to be a multiple of " *
                                 "the vector width W = $W"))
        return new{MR,NR,T,W}(descriptor)
    end
end

"""
    _default_lanewidth(::Type{T}) -> Int

Default `SIMD.Vec` lane count for scalar type `T`, used only by the
3-argument `SIMDKernel` constructor. One 256-bit register's worth of lanes:
4 for `Float64`, 8 for `Float32`. Not a hardware-detected or tuned value —
see design doc section 5, "Do not extrapolate this example into default
tuning settings for other CPUs or types."
"""
_default_lanewidth(::Type{Float64}) = 4
_default_lanewidth(::Type{Float32}) = 8

function SIMDKernel(::Val{MR}, ::Val{NR}, ::Type{T}, ::Val{W}) where {MR,NR,T,W}
    return SIMDKernel{MR,NR,T,W}(KernelDescriptor(Val(MR), Val(NR), T))
end
function SIMDKernel(::Val{MR}, ::Val{NR}, ::Type{T}) where {MR,NR,T}
    return SIMDKernel(Val(MR), Val(NR), T, Val(_default_lanewidth(T)))
end

mr(k::SIMDKernel) = mr(k.descriptor)
nr(k::SIMDKernel) = nr(k.descriptor)
scalartype(k::SIMDKernel) = scalartype(k.descriptor)
packed_a_offset(k::SIMDKernel, i::Int, p::Int) = packed_a_offset(k.descriptor, i, p)
packed_b_offset(k::SIMDKernel, j::Int, p::Int) = packed_b_offset(k.descriptor, j, p)
packed_a_length(k::SIMDKernel, kc::Int) = packed_a_length(k.descriptor, kc)
packed_b_length(k::SIMDKernel, kc::Int) = packed_b_length(k.descriptor, kc)

"""
    lanewidth(kernel::SIMDKernel) -> Int

The kernel's `SIMD.Vec` lane width `W`.
"""
lanewidth(::SIMDKernel{MR,NR,T,W}) where {MR,NR,T,W} = W

"""
    avecs_per_column(kernel::SIMDKernel) -> Int

`mr(kernel) ÷ lanewidth(kernel)`: the number of full-width A vectors (and
thus accumulator vectors) per output column.
"""
avecs_per_column(::SIMDKernel{MR,NR,T,W}) where {MR,NR,T,W} = MR ÷ W

# Integration (main process, matching the pack_a!/pack_b! forwarding pattern
# established for ScalarKernel in src/kernel.jl / docs/decisions.md): pack_a!/
# pack_b! dispatch on a bare KernelDescriptor, so forward SIMDKernel to it.
pack_a!(packed::Vector, source::QSTile, kernel::SIMDKernel, transform) =
    pack_a!(packed, source, kernel.descriptor, transform)
pack_b!(packed::Vector, source::QSTile, kernel::SIMDKernel, transform) =
    pack_b!(packed, source, kernel.descriptor, transform)

# ----------------------------------------------------------------------------
# zero_accumulator, accumulate
# ----------------------------------------------------------------------------

"""
    zero_accumulator(kernel::SIMDKernel{MR,NR,T,W}) -> NTuple{NV,SIMD.Vec{W,T}}

Return a logical `MR`-by-`NR` zero accumulator, represented as an immutable
tuple of `NV = (MR÷W)*NR` zero `Vec{W,T}` values (design doc section 8: "an
ordinary heap array of accumulators is not the intended fast path"). Entry
`(v, j)` (`v` the row-vector index in `0:MR÷W-1`, `j` the output column in
`0:NR-1`) lives at 1-based tuple position `v + (MR÷W)*j + 1`; physical row
`i` of that vector is lane `i - v*W + 1` (1-based `SIMD.Vec` indexing).
"""
function zero_accumulator(kernel::SIMDKernel{MR,NR,T,W}) where {MR,NR,T,W}
    NVECA = MR ÷ W
    z = zero(Vec{W,T})
    return ntuple(_ -> z, Val(NVECA * NR))
end

# The fully unrolled, closure-free K-step body: one vector load per A
# row-vector, one scalar load per B column, NVECA*NR FMAs, entirely generated
# as straight-line code from the static (MR, NR, T, W) combination. See this
# file's header comment for why this is a `@generated` function rather than
# `ntuple(f, Val(NV)) do ... end` closures over the reassigned accumulator.
@generated function _accumulate_step(kernel::SIMDKernel{MR,NR,T,W}, acc::NTuple{NV,Vec{W,T}},
                                      packed_a::AbstractVector{T}, packed_b::AbstractVector{T},
                                      p::Int) where {MR,NR,T,W,NV}
    NVECA = MR ÷ W
    NVECA * NR == NV ||
        throw(ArgumentError("_accumulate_step: accumulator length $NV does not match " *
                             "(mr÷W)*nr = $(NVECA * NR) for MR=$MR, NR=$NR, W=$W"))

    avars = [Symbol(:a, v) for v in 0:(NVECA - 1)]
    bvars = [Symbol(:b, j) for j in 0:(NR - 1)]

    load_a = [:( $(avars[v + 1]) = vload(Vec{$W,$T}, packed_a, packed_a_offset(kernel, $(v * W), p) + 1) )
              for v in 0:(NVECA - 1)]
    load_b = [:( $(bvars[j + 1]) = packed_b[packed_b_offset(kernel, $j, p) + 1] )
              for j in 0:(NR - 1)]

    acc_exprs = Vector{Any}(undef, NV)
    for j in 0:(NR - 1), v in 0:(NVECA - 1)
        idx = v + NVECA * j + 1
        acc_exprs[idx] = :( muladd($(avars[v + 1]), $(bvars[j + 1]), acc[$idx]) )
    end

    return quote
        Base.@_inline_meta
        @inbounds begin
            $(load_a...)
            $(load_b...)
            return $(Expr(:tuple, acc_exprs...))
        end
    end
end

"""
    accumulate(kernel::SIMDKernel, acc, packed_a, packed_b, kc::Int) -> acc

SIMD counterpart of `ScalarKernel`'s `accumulate` (see `src/kernel.jl`'s
docstring for why this extends `Base.accumulate` rather than introducing a
colliding top-level binding). Same logical contract: `kc == 0` returns `acc`
unchanged without reading `packed_a`/`packed_b`; otherwise updates `acc` with
`kc` K-steps of the packed product in increasing `p` order, supporting a
nonzero incoming accumulator. Never reads or writes the destination tensor.

Not bitwise identical to `ScalarKernel`'s `accumulate` on the same inputs
(FMA grouping and evaluation order differ between the vector and scalar
implementations) — compare with a numerical tolerance, never `==`.

Requires `packed_a` to support `SIMD.vload` (a `Vector{T}` or a contiguous,
unit-range `view` of one); `packed_b` may be any `AbstractVector{T}` since it
is only ever read with ordinary scalar `getindex`.
"""
function Base.accumulate(kernel::SIMDKernel{MR,NR,T,W}, acc::NTuple{NV,Vec{W,T}},
                          packed_a::AbstractVector{T}, packed_b::AbstractVector{T},
                          kc::Int) where {MR,NR,T,W,NV}
    kc == 0 && return acc
    kc > 0 || throw(ArgumentError("accumulate requires kc >= 0, got kc = $kc"))
    @inbounds for p in 0:(kc - 1)
        acc = _accumulate_step(kernel, acc, packed_a, packed_b, p)
    end
    return acc
end

# ----------------------------------------------------------------------------
# Output update: scale_tile! is reused as-is from src/kernel.jl (it dispatches
# on `destination::QSTile` alone, with no kernel argument, so it is already
# shared — see that file's definition).
# ----------------------------------------------------------------------------

_unit_stride_rows(ax::AffineAxis) = ax.stride == 1
_unit_stride_rows(::ScatterAxis) = false

@inline function _acc_lane(acc::NTuple{NV,Vec{W,T}}, v::Int, j::Int, lane1::Int,
                            ::Val{NVECA}) where {NV,W,T,NVECA}
    return acc[v + NVECA * j + 1][lane1]
end

"""
    store_tile!(destination::QSTile, acc::NTuple{NV,SIMD.Vec{W,T}}, alpha::T, beta::T, kernel::SIMDKernel) -> destination

SIMD counterpart of `ScalarKernel`'s `store_tile!` (`src/kernel.jl`). Same
logical contract (design doc section 9): for every valid destination
coordinate `(i,j)` in `0:m-1 x 0:n-1`,

    C[i,j] = alpha * R[i,j] + beta * C[i,j]

with the identical alpha/beta shortcuts (`alpha==0` never reads the
accumulator; `beta==0` never reads old `C`; `beta==1` skips the
multiplication). Only the valid `m`-by-`n` rectangle is touched, so
accumulator lanes at `i>=m`/`j>=n` (kernel padding lanes, possibly nonfinite —
design doc section 8) are never read here and cannot propagate into the
stored output.

Two code paths, matching design doc section 9's "Unit row stride: use vector
loads/stores where valid... Other affine addressing: scalar strided handling
is sufficient initially... Column addressing is independent of row
addressing":

  * When `destination.rows` is an `AffineAxis` with `stride == 1` *and*
    `destination.storage` is a plain `Vector{T}`: for each valid column `j`
    (`destination.cols` may be affine or scattered — column addressing does
    not affect this choice), the full `m ÷ W` whole-width row blocks are
    updated with a genuine `SIMD.Vec{W,T}` load/store each; the remaining
    `m % W` rows (the tail) are updated one at a time via ordinary scalar
    loads/stores, extracting the corresponding lane of the same accumulator
    vector via `SIMD.Vec` indexing. The tail is deliberately scalar rather
    than a hardware-masked vector op: a masked `vload`/`vstore` still bounds-
    checks (and, at the LLVM level, still requires addressability of) the
    *entire* `W`-wide window even though only some lanes are read/written,
    and nothing in this package's contract guarantees a destination buffer
    has that much room past its last valid row (`checked_tile_storage_bounds`
    only validates the individual valid `(i,j)` addresses actually used, not
    every address in a partial vector's footprint). The scalar tail is
    exactly as safe as `ScalarKernel`'s store and never over-reads.
  * Otherwise (scattered rows, non-unit affine row stride, or non-`Vector`
    storage): every coordinate uses the scalar path, exactly as above without
    a vectorized fast branch — logically identical to `ScalarKernel`'s
    `store_tile!` on a `QSTile`, just extracting each accumulator scalar from
    its `SIMD.Vec` lane instead of a `Matrix`.

An empty destination (`m == 0` or `n == 0`) is a no-op.
"""
function store_tile!(destination::QSTile, acc::NTuple{NV,Vec{W,T}},
                      alpha::T, beta::T, kernel::SIMDKernel{MR,NR,T,W}) where {MR,NR,T,W,NV}
    m = nrows(destination)
    n = ncols(destination)
    (m == 0 || n == 0) && return destination

    if iszero(alpha)
        scale_tile!(destination, beta)
        return destination
    end

    NVECA = MR ÷ W
    nfull = m ÷ W  # whole W-row blocks entirely inside [0, m)

    if _unit_stride_rows(destination.rows) && destination.storage isa Vector{T}
        storage = destination.storage
        rows = destination.rows
        cols = destination.cols
        rowbase0 = destination.base + rows.base  # zero-based address at (i=0, j=0)'s row contribution
        @inbounds for j in 0:(n - 1)
            colbase = rowbase0 + axis_offset(cols, j)  # zero-based address of (i=0, j)
            for v in 0:(nfull - 1)
                idx = colbase + v * W + 1  # one-based storage index of row v*W
                rvec = acc[v + NVECA * j + 1]
                if iszero(beta)
                    outvec = alpha * rvec
                elseif isone(beta)
                    outvec = muladd(alpha, rvec, vload(Vec{W,T}, storage, idx))
                else
                    outvec = muladd(alpha, rvec, beta * vload(Vec{W,T}, storage, idx))
                end
                vstore(outvec, storage, idx)
            end
            for i in (nfull * W):(m - 1)
                idx = colbase + i + 1
                r = _acc_lane(acc, i ÷ W, j, (i % W) + 1, Val(NVECA))
                if iszero(beta)
                    storage[idx] = alpha * r
                elseif isone(beta)
                    storage[idx] = muladd(alpha, r, storage[idx])
                else
                    storage[idx] = muladd(alpha, r, beta * storage[idx])
                end
            end
        end
        return destination
    end

    @inbounds for j in 0:(n - 1), i in 0:(m - 1)
        r = _acc_lane(acc, i ÷ W, j, (i % W) + 1, Val(NVECA))
        if iszero(beta)
            tile_store!(destination, i, j, alpha * r)
        elseif isone(beta)
            tile_store!(destination, i, j, muladd(alpha, r, tile_load(destination, i, j)))
        else
            tile_store!(destination, i, j, muladd(alpha, r, beta * tile_load(destination, i, j)))
        end
    end
    return destination
end

"""
    execute_tile!(kernel::SIMDKernel, destination::QSTile, packed_a, packed_b, kc::Int, alpha, beta) -> destination

SIMD counterpart of `ScalarKernel`'s `execute_tile!` on a `QSTile`
(`src/kernel.jl`); same checked composition of `zero_accumulator`,
`accumulate` and `store_tile!`, the same validation order (destination
extent vs. kernel shape, `kc >= 0`, `checked_tile_storage_bounds` before any
unchecked path — including before the `kc==0`/`alpha==0` short-circuit, per
the Phase 2b Fable review fix this mirrors — then packed-buffer length
against `packed_a_length`/`packed_b_length`), and the same short-circuit
(`kc==0` or `alpha==0`: apply only beta scaling, never read `packed_a`/
`packed_b`).

Numerically matches `ScalarKernel`'s `execute_tile!` on the same inputs only
to within a tolerance (never bitwise): the accumulation order and FMA
grouping differ (design doc section 8: "FMA behavior and panel grouping can
change rounding").
"""
function execute_tile!(kernel::SIMDKernel{MR,NR,T,W}, destination::QSTile,
                        packed_a::AbstractVector{T}, packed_b::AbstractVector{T},
                        kc::Int, alpha, beta) where {MR,NR,T,W}
    m = nrows(destination)
    n = ncols(destination)
    m <= MR || throw(ArgumentError("destination valid row extent $m exceeds mr(kernel) = $MR"))
    n <= NR || throw(ArgumentError("destination valid column extent $n exceeds nr(kernel) = $NR"))
    kc >= 0 || throw(ArgumentError("execute_tile! requires kc >= 0, got kc = $kc"))

    alphaT = convert(T, alpha)
    betaT = convert(T, beta)

    (m == 0 || n == 0) && return destination

    # Fable review (Phase 2b) fix, preserved here: validate reachable
    # destination storage bounds before any unchecked path, including the
    # short-circuit below.
    checked_tile_storage_bounds(destination)

    if kc == 0 || iszero(alphaT)
        scale_tile!(destination, betaT)
        return destination
    end

    length(packed_a) >= packed_a_length(kernel, kc) ||
        throw(DimensionMismatch("execute_tile!: packed_a has length $(length(packed_a)), " *
                                 "need at least packed_a_length(kernel, kc=$kc) = $(packed_a_length(kernel, kc))"))
    length(packed_b) >= packed_b_length(kernel, kc) ||
        throw(DimensionMismatch("execute_tile!: packed_b has length $(length(packed_b)), " *
                                 "need at least packed_b_length(kernel, kc=$kc) = $(packed_b_length(kernel, kc))"))

    acc = zero_accumulator(kernel)
    acc = accumulate(kernel, acc, packed_a, packed_b, kc)
    store_tile!(destination, acc, alphaT, betaT, kernel)
    return destination
end
